### ISSUE TITLE
Get this on MELPA

### ISSUE THREAD

**Issue by lf94** [vyp/gruvbox-emacs#1]
Please? :) I see this code is similar to that of the other popular gruvbox theme for emacs. My problem with the other is the lack of a light theme.

Maybe call yours gruvbox2-theme on it or something.

**Comment by vyp** [comment]
Hope you don't mind the mention @purcell, IIRC there were already a few gruvbox themes on melpa already (cannot check right now), but do you think there's room for another? I know obviously it would be best if I put these changes into the original gruvbox, but in addition to the light variant, I also made quite a lot of other subjective changes to lots of things and also having light/dark variants and contrast options changed a lot of other stuff too and I don't have the desire or time to coordinate all that unfortunately, at least not for quite a while. :( (Originally I made this a separate repo just to make it easier to install for others, but I've just all this time being using this theme as if it was my own personal theme, despite being in a separate repo.) 

I'm aware that the code is quite a mess and likely does not fit to the standard package.el requirements, I did this before learning about that. And also the lack of documentation. I'll have time to fix it up a bit at the end of the week if needed.

@lf94 In the meantime, do you know how to install it normally/manually?

**Comment by lf94** [comment]
I've looked on melpa and there is only one gruvbox theme. The other two are based on it which really makes them their own themes...they are called suscolors-theme and darktooth-theme and don't offer light versions.

I think it's more than acceptable to submit yours as gruvbox2 or maybe called it 'gruxbox-light' and only include the light version. Best of both worlds is to get someone to do a pull request with the popular one and this one.

In any case, I know how to manually install themes. Thanks for the quick response @vyp!

**Comment by jasonm23** [comment]
:+1: gruvbox-light or merge with Gruvbox, you're welcome to become a contributor.

**Comment by vyp** [comment]
See https://github.com/greduan/emacs-theme-gruvbox/issues/45. FYI this repository is going to be deleted.
